#ifndef INCLUDE_ROTARY_ENCODER_CONFIG_H
#define INCLUDE_ROTARY_ENCODER_CONFIG_H

#define DEFAULT_PIN_A_PINMODE       PullUp
#define DEFAULT_PIN_B_PINMODE       PullUp
#define DEFAULT_PIN_Z_PINMODE       PullUp

#endif //INCLUDE_ROTARY_ENCODER_CONFIG_H